# Welcome to Jekyll!
#
# Solar theme configuration

# Site settings
name: Solar Theme
url: https://bajal.github.io
description: A stylish blog using the Solarized color palette
author: Your Name
email: your-email@example.com

# Build settings
markdown: kramdown

# Permalink structure
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Social links
github_username: bajal
# twitter_username: your_twitter

# Timezone
timezone: America/Los_Angeles

