version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll-blog
    platform: linux/amd64
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --force_polling --livereload
    ports:
      - 4000:4000
      - 35729:35729  # For livereload
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    stdin_open: true
    tty: true

