# Project information
site_name: "Bajal's Notes"
site_description: "Random Notes and Tidbits"
site_author: "Mohiyudeen Bajal"
#site_url: ''

# Repository
repo_name: "bajal/bajal.github.io"
repo_url: "https://github.com/bajal/bajal.github.io"
edit_uri: edit/main/docs/

theme:
  name: material
  language: "en"
  palette:
    primary: "indigo"
    accent: "blue"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - tabs
    - navigation.instant
    - navigation.tabs
    - instant

nav:
  - Home: index.md
  - Notes:
      - Git: git_tips.md
      - Golang:
          - Intro: golang.md
          - Learning: learning_go.md
      - Running Local SFTP server: sftpgo.md
      - AWS:
          - SAA02: aws-saa02.md
